server:
  port: 8010
spring:
  profiles:
    active: dev
  application:
    name: admin-server
  datasource:
    continue-on-error: true
    druid:
      max-wait: 15000
      pool-prepared-statements: false
      max-open-prepared-statements: 0
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      remove-abandoned: false
      remove-abandoned-timeout: 1800
      log-abandoned: true
      filters: stat,slf4j
      web-stat-filter:
        session-stat-enable: false
logging:
  level:
    root: WARN
su:
  cache:
    redisson:
      config-file: redisson-${spring.profiles.active}.yml
  api:
    doc:
      title: 系统管理服务
      description: 系统管理服务接口
      version: 1.0
      base-package: com.github.jnoee.xo.cloud.demo.admin.api
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS