server:
  port: 8020
spring:
  profiles:
    active: dev
  application:
    name: film-server
  output:
    ansi:
      enabled: never
logging:
  level:
    root: WARN
xo:
  cache:
      config-file: redisson-${spring.profiles.active}.yml
  api:
    doc:
      title: 影片服务
      description: 影片服务接口
      version: 1.0
      base-package: com.github.jnoee.xo.cloud.demo.film.api
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS